title: buzl.uk
url: https://www.buzl.uk
canonical: https://www.buzl.uk
description: kaangiray26's personal website
incremental: false
timezone: Europe/Berlin
paginate: 30
plugins:
    - jekyll-paginate
paginate_path: "/blog/page:num/"
exclude: ["README.md", "jekyll", "LICENSE"]
