#!/bin/bash

# Check if no arguments passed
if [ $# -eq 0 ]; then
    echo "No arguments provided, exiting..."
    exit 1
fi

# Show help
if [ "$1" == "help" ]; then
    echo "Usage: jekyll <command>"
    echo ""
    echo "Commands:"
    echo "  build       Build the site"
    echo "  serve       Serve the site"
    echo "  deploy      Deploy the site"
    echo "  help        Show this help message"
fi

# Build
if [ "$1" == "build" ]; then
    echo "Building site with docker image..."
    docker run --rm --volume="$PWD:/srv/jekyll" -it jekyll/jekyll jekyll build -d docs
    echo "Site built to the ./docs folder."
fi

# Serve
if [ "$1" == "serve" ]; then
    echo "Serving the site with docker image..."
    docker run --rm --volume="$PWD:/srv/jekyll" -p 4000:4000 -p 3000:3000 -it jekyll/jekyll sh -c "bundle add webrick ; echo '==> ignoring any errors ʅʕ•ᴥ•ʔʃ' ; bundle install ; jekyll serve --livereload --watch --drafts --livereload-port 3000"
fi

# Deploy
if [ "$1" == "deploy" ]; then
    echo "Building site with docker image..."
    docker run --rm --volume="$PWD:/srv/jekyll" -it jekyll/jekyll jekyll build -d docs
    echo "Site built to the ./docs folder."
    echo "Pushing to GitHub..."
    git add -A && git commit -m "Update site" && git push
    echo "done."
fi
