# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for automatically sending webmentions when a Jekyll site is built and deployed to GitHub Pages
name: Send Webmentions

on: deployment

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    # Build job
    build:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - name: Checkout webmention repository
              uses: actions/checkout@v4
              with:
                  repository: kaangiray26/webmention

            - name: release-downloader
              uses: robinraju/release-downloader@v1.11
              with:
                  latest: true
                  fileName: "*.json"
                  tarBall: false
                  zipBall: false

            - name: Unnecessary pip install
              run: python3 -m pip install --upgrade pip

            - name: Install python dependencies
              run: python3 -m pip install -r requirements.txt

            - name: Run python script
              run: python3 main.py

            - name: Release
              uses: softprops/action-gh-release@v2.0.6
              with:
                  tag_name: webmentions
                  token: ${{ secrets.TOKEN }}
                  files: |
                      ignored.json
                      sent.json
